apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flagger
  namespace: istio-system
  annotations:
    fluxcd.io/tag.chart-image: semver:~0
spec:
  releaseName: flagger
  chart:
    repository: https://flagger.app
    name: flagger
    version: 0.20.3
  values:
    metricsServer: http://prometheus.istio-system:9090
    image:
      repository: weaveworks/flagger
      tag: 0.20.3
      pullPolicy: IfNotPresent
    meshProvider: istio
