apiVersion: cluster.k8s.io/v1alpha1
kind: Cluster
metadata:
  name: example
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.96.0.0/12
  providerSpec:
    value:
      apiVersion: baremetalproviderspec/v1alpha1
      cri:
        kind: docker
        package: docker-ce
        version: 18.09.7
      imageRepository: 172.17.0.4:5000
      kind: BareMetalClusterProviderSpec
      os:
        files:
        - destination: /etc/yum.repos.d/kubernetes.repo
          source:
            configmap: repo
            key: kubernetes.repo
        - destination: /etc/yum.repos.d/docker-ce.repo
          source:
            configmap: repo
            key: docker-ce.repo
        - destination: /etc/docker/daemon.json
          source:
            configmap: docker
            key: daemon.json
      user: root
