---
apiVersion: v1
kind: Secret
metadata:
  name: csi-s3-secret
  namespace: csi-s3-system
stringData:
  accessKeyID: minio
  secretAccessKey: minio123
  # For AWS set it to "https://s3.<region>.amazonaws.com"
  endpoint: http://minio-service.kubeflow:9000
  # If not on S3, set it to ""
  region: ""
