apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: pytorch-operator
    app.kubernetes.io/component: pytorch
    app.kubernetes.io/instance: pytorch-operator-v0.7.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: pytorch-operator
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v0.7.0
    kustomize.component: pytorch-operator
  name: pytorch-operator
  namespace: kubeflow
---
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.kubeflow.org/aggregate-to-kubeflow-pytorchjobs-admin: "true"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: pytorch
    app.kubernetes.io/instance: pytorch-operator-v0.7.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: pytorch-operator
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v0.7.0
    kustomize.component: pytorch-operator
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-admin: "true"
  name: kubeflow-pytorchjobs-admin
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: pytorch
    app.kubernetes.io/instance: pytorch-operator-v0.7.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: pytorch-operator
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v0.7.0
    kustomize.component: pytorch-operator
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-edit: "true"
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-pytorchjobs-admin: "true"
  name: kubeflow-pytorchjobs-edit
rules:
- apiGroups:
  - kubeflow.org
  resources:
  - pytorchjobs
  - pytorchjobs/status
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - deletecollection
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: pytorch
    app.kubernetes.io/instance: pytorch-operator-v0.7.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: pytorch-operator
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v0.7.0
    kustomize.component: pytorch-operator
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-view: "true"
  name: kubeflow-pytorchjobs-view
rules:
- apiGroups:
  - kubeflow.org
  resources:
  - pytorchjobs
  - pytorchjobs/status
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: pytorch-operator
    app.kubernetes.io/component: pytorch
    app.kubernetes.io/instance: pytorch-operator-v0.7.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: pytorch-operator
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v0.7.0
    kustomize.component: pytorch-operator
  name: pytorch-operator
rules:
- apiGroups:
  - kubeflow.org
  resources:
  - pytorchjobs
  - pytorchjobs/status
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - events
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: pytorch-operator
    app.kubernetes.io/component: pytorch
    app.kubernetes.io/instance: pytorch-operator-v0.7.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: pytorch-operator
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v0.7.0
    kustomize.component: pytorch-operator
  name: pytorch-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pytorch-operator
subjects:
- kind: ServiceAccount
  name: pytorch-operator
  namespace: kubeflow
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8443"
    prometheus.io/scrape: "true"
  labels:
    app: pytorch-operator
    app.kubernetes.io/component: pytorch
    app.kubernetes.io/instance: pytorch-operator-v0.7.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: pytorch-operator
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v0.7.0
    kustomize.component: pytorch-operator
  name: pytorch-operator
  namespace: kubeflow
spec:
  ports:
  - name: monitoring-port
    port: 8443
    targetPort: 8443
  selector:
    app.kubernetes.io/component: pytorch
    app.kubernetes.io/instance: pytorch-operator-v0.7.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: pytorch-operator
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v0.7.0
    kustomize.component: pytorch-operator
    name: pytorch-operator
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: pytorch
    app.kubernetes.io/instance: pytorch-operator-v0.7.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: pytorch-operator
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v0.7.0
    kustomize.component: pytorch-operator
  name: pytorch-operator
  namespace: kubeflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: pytorch
      app.kubernetes.io/instance: pytorch-operator-v0.7.0
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/name: pytorch-operator
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: v0.7.0
      kustomize.component: pytorch-operator
      name: pytorch-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: pytorch
        app.kubernetes.io/instance: pytorch-operator-v0.7.0
        app.kubernetes.io/managed-by: kfctl
        app.kubernetes.io/name: pytorch-operator
        app.kubernetes.io/part-of: kubeflow
        app.kubernetes.io/version: v0.7.0
        kustomize.component: pytorch-operator
        name: pytorch-operator
    spec:
      containers:
      - command:
        - /pytorch-operator.v1
        - --alsologtostderr
        - -v=1
        - --monitoring-port=8443
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: gcr.io/kubeflow-images-public/pytorch-operator:v0.7.0
        name: pytorch-operator
      serviceAccountName: pytorch-operator
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app.kubernetes.io/component: pytorch
    app.kubernetes.io/instance: pytorch-operator-v0.7.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: pytorch-operator
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v0.7.0
  name: pytorch-operator
  namespace: kubeflow
spec:
  addOwnerRef: true
  componentKinds:
  - group: core
    kind: Service
  - group: apps
    kind: Deployment
  - group: core
    kind: ConfigMap
  - group: core
    kind: ServiceAccount
  - group: kubeflow.org
    kind: PyTorchJob
  descriptor:
    description: Pytorch-operator allows users to create and manage the "PyTorchJob"
      custom resource.
    keywords:
    - pytorchjob
    - pytorch-operator
    - pytorch-training
    links:
    - description: About
      url: https://github.com/kubeflow/pytorch-operator
    - description: Docs
      url: https://www.kubeflow.org/docs/reference/pytorchjob/v1/pytorch/
    maintainers:
    - email: johnugeo@cisco.com
      name: Johnu George
    owners:
    - email: johnugeo@cisco.com
      name: Johnu George
    type: pytorch-operator
    version: v1
  selector:
    matchLabels:
      app.kubernetes.io/component: pytorch
      app.kubernetes.io/instance: pytorch-operator-v0.7.0
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/name: pytorch-operator
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: v0.7.0
