apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/component: pytorch
    app.kubernetes.io/instance: pytorch-job-crds-v0.7.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: pytorch-job-crds
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v0.7.0
  name: pytorchjobs.kubeflow.org
spec:
  additionalPrinterColumns:
  - JSONPath: .status.conditions[-1:].type
    name: State
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: kubeflow.org
  names:
    kind: PyTorchJob
    plural: pytorchjobs
    singular: pytorchjob
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            pytorchReplicaSpecs:
              properties:
                Master:
                  properties:
                    replicas:
                      maximum: 1
                      minimum: 1
                      type: integer
                Worker:
                  properties:
                    replicas:
                      minimum: 1
                      type: integer
  versions:
  - name: v1
    served: true
    storage: true
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app.kubernetes.io/component: pytorch
    app.kubernetes.io/instance: pytorch-job-crds-v0.7.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: pytorch-job-crds
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v0.7.0
  name: pytorch-job-crds
  namespace: kubeflow
spec:
  addOwnerRef: true
  componentKinds:
  - group: core
    kind: Service
  - group: apps
    kind: Deployment
  - group: core
    kind: ServiceAccount
  - group: kubeflow.org
    kind: PyTorchJob
  descriptor:
    description: Pytorch-job-crds contains the "PyTorchJob" custom resource definition.
    keywords:
    - pytorchjob
    - pytorch-operator
    - pytorch-training
    links:
    - description: About
      url: https://github.com/kubeflow/pytorch-operator
    - description: Docs
      url: https://www.kubeflow.org/docs/reference/pytorchjob/v1/pytorch/
    maintainers:
    - email: johnugeo@cisco.com
      name: Johnu George
    owners:
    - email: johnugeo@cisco.com
      name: Johnu George
    type: pytorch-job-crds
    version: v1
  selector:
    matchLabels:
      app.kubernetes.io/component: pytorch
      app.kubernetes.io/instance: pytorch-job-crds-v0.7.0
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/name: pytorch-job-crds
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: v0.7.0
