apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/component: tfjob
    app.kubernetes.io/instance: tf-job-crds-v0.7.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: tf-job-crds
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v0.7.0
  name: tfjobs.kubeflow.org
spec:
  additionalPrinterColumns:
  - JSONPath: .status.conditions[-1:].type
    name: State
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: kubeflow.org
  names:
    kind: TFJob
    plural: tfjobs
    singular: tfjob
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            tfReplicaSpecs:
              properties:
                Chief:
                  properties:
                    replicas:
                      maximum: 1
                      minimum: 1
                      type: integer
                PS:
                  properties:
                    replicas:
                      minimum: 1
                      type: integer
                Worker:
                  properties:
                    replicas:
                      minimum: 1
                      type: integer
  versions:
  - name: v1
    served: true
    storage: true
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app.kubernetes.io/component: tfjob
    app.kubernetes.io/instance: tf-job-crds-v0.7.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: tf-job-crds
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v0.7.0
  name: tf-job-crds
  namespace: kubeflow
spec:
  addOwnerRef: true
  componentKinds:
  - group: core
    kind: Service
  - group: apps
    kind: Deployment
  - group: core
    kind: ServiceAccount
  - group: kubeflow.org
    kind: TFJob
  descriptor:
    description: Tf-job-crds contains the "TFJob" custom resource definition.
    keywords:
    - tfjob
    - tf-operator
    - tf-training
    links:
    - description: About
      url: https://github.com/kubeflow/tf-operator
    - description: Docs
      url: https://www.kubeflow.org/docs/reference/tfjob/v1/tensorflow/
    maintainers:
    - email: ricliu@google.com
      name: Richard Liu
    owners:
    - email: ricliu@google.com
      name: Richard Liu
    type: tf-job-crds
    version: v1
  selector:
    matchLabels:
      app.kubernetes.io/component: tfjob
      app.kubernetes.io/instance: tf-job-crds-v0.7.0
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/name: tf-job-crds
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: v0.7.0
