apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: ml-pipeline-persistenceagent
    app.kubernetes.io/component: persistent-agent
    app.kubernetes.io/instance: persistent-agent-0.1.31
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: persistent-agent
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: 0.1.31
  name: ml-pipeline-persistenceagent
  namespace: kubeflow
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: ml-pipeline-persistenceagent
    app.kubernetes.io/component: persistent-agent
    app.kubernetes.io/instance: persistent-agent-0.1.31
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: persistent-agent
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: 0.1.31
  name: ml-pipeline-persistenceagent
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - scheduledworkflows
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: ml-pipeline-persistenceagent
    app.kubernetes.io/component: persistent-agent
    app.kubernetes.io/instance: persistent-agent-0.1.31
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: persistent-agent
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: 0.1.31
  name: ml-pipeline-persistenceagent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: ml-pipeline-persistenceagent
  namespace: kubeflow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ml-pipeline-persistenceagent
    app.kubernetes.io/component: persistent-agent
    app.kubernetes.io/instance: persistent-agent-0.1.31
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: persistent-agent
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: 0.1.31
  name: ml-pipeline-persistenceagent
  namespace: kubeflow
spec:
  selector:
    matchLabels:
      app: ml-pipeline-persistenceagent
      app.kubernetes.io/component: persistent-agent
      app.kubernetes.io/instance: persistent-agent-0.1.31
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/name: persistent-agent
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: 0.1.31
  template:
    metadata:
      labels:
        app: ml-pipeline-persistenceagent
        app.kubernetes.io/component: persistent-agent
        app.kubernetes.io/instance: persistent-agent-0.1.31
        app.kubernetes.io/managed-by: kfctl
        app.kubernetes.io/name: persistent-agent
        app.kubernetes.io/part-of: kubeflow
        app.kubernetes.io/version: 0.1.31
    spec:
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: gcr.io/ml-pipeline/persistenceagent:0.1.31
        imagePullPolicy: IfNotPresent
        name: ml-pipeline-persistenceagent
      serviceAccountName: ml-pipeline-persistenceagent
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app.kubernetes.io/component: persistent-agent
    app.kubernetes.io/instance: persistent-agent-0.1.31
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: persistent-agent
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: 0.1.31
  name: persistent-agent
  namespace: kubeflow
spec:
  addOwnerRef: true
  componentKinds:
  - group: core
    kind: ConfigMap
  - group: apps
    kind: Deployment
  descriptor:
    description: ""
    keywords:
    - persistent-agent
    - kubeflow
    links:
    - description: About
      url: ""
    maintainers: []
    owners: []
    type: persistent-agent
    version: v1beta1
  selector:
    matchLabels:
      app.kubernetes.io/component: persistent-agent
      app.kubernetes.io/instance: persistent-agent-0.1.31
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/name: persistent-agent
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: 0.1.31
