apiVersion: v1
kind: Service
metadata:
  labels:
    app: ml-pipeline-visualizationserver
    app.kubernetes.io/component: pipeline-visualization-service
    app.kubernetes.io/instance: pipeline-visualization-service-0.1.31
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: pipeline-visualization-service
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: 0.1.31
  name: ml-pipeline-ml-pipeline-visualizationserver
  namespace: kubeflow
spec:
  ports:
  - name: http
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: ml-pipeline-visualizationserver
    app.kubernetes.io/component: pipeline-visualization-service
    app.kubernetes.io/instance: pipeline-visualization-service-0.1.31
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: pipeline-visualization-service
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: 0.1.31
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ml-pipeline-visualizationserver
    app.kubernetes.io/component: pipeline-visualization-service
    app.kubernetes.io/instance: pipeline-visualization-service-0.1.31
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: pipeline-visualization-service
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: 0.1.31
  name: ml-pipeline-ml-pipeline-visualizationserver
  namespace: kubeflow
spec:
  selector:
    matchLabels:
      app: ml-pipeline-visualizationserver
      app.kubernetes.io/component: pipeline-visualization-service
      app.kubernetes.io/instance: pipeline-visualization-service-0.1.31
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/name: pipeline-visualization-service
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: 0.1.31
  template:
    metadata:
      labels:
        app: ml-pipeline-visualizationserver
        app.kubernetes.io/component: pipeline-visualization-service
        app.kubernetes.io/instance: pipeline-visualization-service-0.1.31
        app.kubernetes.io/managed-by: kfctl
        app.kubernetes.io/name: pipeline-visualization-service
        app.kubernetes.io/part-of: kubeflow
        app.kubernetes.io/version: 0.1.31
    spec:
      containers:
      - image: gcr.io/ml-pipeline/visualization-server:0.1.27
        imagePullPolicy: IfNotPresent
        name: ml-pipeline-visualizationserver
        ports:
        - containerPort: 8888
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app.kubernetes.io/component: pipeline-visualization-service
    app.kubernetes.io/instance: pipeline-visualization-service-0.1.31
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: pipeline-visualization-service
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: 0.1.31
  name: pipeline-visualization-service
  namespace: kubeflow
spec:
  addOwnerRef: true
  componentKinds:
  - group: core
    kind: ConfigMap
  - group: apps
    kind: Deployment
  descriptor:
    description: ""
    keywords:
    - pipeline-visualization-service
    - kubeflow
    links:
    - description: About
      url: ""
    maintainers: []
    owners: []
    type: pipeline-visualization-service
    version: v1beta1
  selector:
    matchLabels:
      app.kubernetes.io/component: pipeline-visualization-service
      app.kubernetes.io/instance: pipeline-visualization-service-0.1.31
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/name: pipeline-visualization-service
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: 0.1.31
